crate = "rusqlite"
version = "0.38.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "f1c93dd1c9683b438c392c492109cb702b8090b2bfc8fed6f6e4eb4523f17af3"
crate_archive_sha256 = "f1c93dd1c9683b438c392c492109cb702b8090b2bfc8fed6f6e4eb4523f17af3"
checksum_match = "yes"
upstream_repository = "https://github.com/rusqlite/rusqlite"
upstream_homepage = ""
synced_at_utc = "2026-03-09T16:49:34Z"
history_repo = "lib/vendor-history/rusqlite.git"
history_head = "5aef0ef20c0bd10b243df0668db04171e42196f9"
sync_cmd = "scripts/vendor/inhouse-crate.sh rusqlite 0.38.0"
