crate = "clap"
version = "4.5.60"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "2797f34da339ce31042b27d23607e051786132987f595b02ba4f6a6dffb7030a"
crate_archive_sha256 = "2797f34da339ce31042b27d23607e051786132987f595b02ba4f6a6dffb7030a"
checksum_match = "yes"
upstream_repository = "https://github.com/clap-rs/clap"
upstream_homepage = ""
synced_at_utc = "2026-03-09T16:48:34Z"
history_repo = "lib/vendor-history/clap.git"
history_head = "dc0dce5c27d4a8f6e623fb7aad263d17d94d7d19"
materialized_path = "lib/vendor/clap"
sync_cmd = "scripts/vendor/inhouse-crate.sh clap 4.5.60"
