crate = "clap"
version = "4.6.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "b193af5b67834b676abd72466a96c1024e6a6ad978a1f484bd90b85c94041351"
crate_archive_sha256 = "b193af5b67834b676abd72466a96c1024e6a6ad978a1f484bd90b85c94041351"
checksum_match = "yes"
upstream_repository = "https://github.com/clap-rs/clap"
upstream_homepage = ""
synced_at_utc = "2026-03-18T18:43:50Z"
history_repo = "lib/vendor-history/clap.git"
history_head = "2b9744adfa21ccac060f42fce80cfeebfbcebbe5"
materialized_path = "lib/vendor/clap"
sync_cmd = "scripts/vendor/inhouse-crate.sh clap 4.6.0"
