crate = "ctrlc"
version = "3.5.2"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "e0b1fab2ae45819af2d0731d60f2afe17227ebb1a1538a236da84c93e9a60162"
crate_archive_sha256 = "e0b1fab2ae45819af2d0731d60f2afe17227ebb1a1538a236da84c93e9a60162"
checksum_match = "yes"
upstream_repository = "https://github.com/Detegr/rust-ctrlc.git"
upstream_homepage = "https://github.com/Detegr/rust-ctrlc"
synced_at_utc = "2026-03-09T16:48:36Z"
history_repo = "lib/vendor-history/ctrlc.git"
history_head = "d1e8661047f0425f7a10d44fe3cf04391a9e59b0"
materialized_path = "lib/vendor/ctrlc"
sync_cmd = "scripts/vendor/inhouse-crate.sh ctrlc 3.5.2"
