crate = "futures"
version = "0.3.32"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "8b147ee9d1f6d097cef9ce628cd2ee62288d963e16fb287bd9286455b241382d"
crate_archive_sha256 = "8b147ee9d1f6d097cef9ce628cd2ee62288d963e16fb287bd9286455b241382d"
checksum_match = "yes"
upstream_repository = "https://github.com/rust-lang/futures-rs"
upstream_homepage = "https://rust-lang.github.io/futures-rs"
synced_at_utc = "2026-03-04T16:45:51Z"
history_repo = "lib/vendor-history/futures.git"
history_head = "250364bfd7ce80eee9074e4baf9d3f134f84e11a"
materialized_path = "lib/vendor/futures"
sync_cmd = "scripts/vendor/inhouse-crate.sh futures 0.3.32"
