crate = "regex"
version = "1.12.3"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "e10754a14b9137dd7b1e3e5b0493cc9171fdd105e0ab477f51b72e7f3ac0e276"
crate_archive_sha256 = "e10754a14b9137dd7b1e3e5b0493cc9171fdd105e0ab477f51b72e7f3ac0e276"
checksum_match = "yes"
upstream_repository = "https://github.com/rust-lang/regex"
upstream_homepage = "https://github.com/rust-lang/regex"
synced_at_utc = "2026-03-04T16:45:52Z"
history_repo = "lib/vendor-history/regex.git"
history_head = "140d77161444f8975123b2c394d360022d17a949"
materialized_path = "lib/vendor/regex"
sync_cmd = "scripts/vendor/inhouse-crate.sh regex 1.12.3"
