crate = "reqwest"
version = "0.13.2"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "ab3f43e3283ab1488b624b44b0e988d0acea0b3214e694730a055cb6b2efa801"
crate_archive_sha256 = "ab3f43e3283ab1488b624b44b0e988d0acea0b3214e694730a055cb6b2efa801"
checksum_match = "yes"
upstream_repository = "https://github.com/seanmonstar/reqwest"
upstream_homepage = ""
synced_at_utc = "2026-03-09T16:49:10Z"
history_repo = "lib/vendor-history/reqwest.git"
history_head = "b0189fa9fb0cba412eb64d96992558da9cd6372f"
materialized_path = "lib/vendor/reqwest"
sync_cmd = "scripts/vendor/inhouse-crate.sh reqwest 0.13.2"
