crate = "rusqlite"
version = "0.39.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "a0d2b0146dd9661bf67bb107c0bb2a55064d556eeb3fc314151b957f313bcd4e"
crate_archive_sha256 = "a0d2b0146dd9661bf67bb107c0bb2a55064d556eeb3fc314151b957f313bcd4e"
checksum_match = "yes"
upstream_repository = "https://github.com/rusqlite/rusqlite"
upstream_homepage = ""
synced_at_utc = "2026-03-18T18:43:53Z"
history_repo = "lib/vendor-history/rusqlite.git"
history_head = "ec74f8123a7ab7973c969dd538a681e5838461a4"
materialized_path = "lib/vendor/rusqlite"
sync_cmd = "scripts/vendor/inhouse-crate.sh rusqlite 0.39.0"
