crate = "tokio"
version = "1.50.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "27ad5e34374e03cfffefc301becb44e9dc3c17584f414349ebe29ed26661822d"
crate_archive_sha256 = "27ad5e34374e03cfffefc301becb44e9dc3c17584f414349ebe29ed26661822d"
checksum_match = "yes"
upstream_repository = "https://github.com/tokio-rs/tokio"
upstream_homepage = "https://tokio.rs"
synced_at_utc = "2026-03-09T16:49:10Z"
history_repo = "lib/vendor-history/tokio.git"
history_head = "65a5636827a1b6dcc7f808d8cc71be60342db1b6"
materialized_path = "lib/vendor/tokio"
sync_cmd = "scripts/vendor/inhouse-crate.sh tokio 1.50.0"
