crate = "toml"
version = "1.0.7+spec-1.1.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "dd28d57d8a6f6e458bc0b8784f8fdcc4b99a437936056fa122cb234f18656a96"
crate_archive_sha256 = "dd28d57d8a6f6e458bc0b8784f8fdcc4b99a437936056fa122cb234f18656a96"
checksum_match = "yes"
upstream_repository = "https://github.com/toml-rs/toml"
upstream_homepage = ""
synced_at_utc = "2026-03-18T18:43:56Z"
history_repo = "lib/vendor-history/toml.git"
history_head = "9bc4b3f4804194d8a42535001fb7c9ddfde6f2b0"
materialized_path = "lib/vendor/toml"
sync_cmd = "scripts/vendor/inhouse-crate.sh toml 1.0.7+spec-1.1.0"
