crate = "tracing-subscriber"
version = "0.3.23"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "cb7f578e5945fb242538965c2d0b04418d38ec25c79d160cd279bf0731c8d319"
crate_archive_sha256 = "cb7f578e5945fb242538965c2d0b04418d38ec25c79d160cd279bf0731c8d319"
checksum_match = "yes"
upstream_repository = "https://github.com/tokio-rs/tracing"
upstream_homepage = "https://tokio.rs"
synced_at_utc = "2026-03-18T18:43:57Z"
history_repo = "lib/vendor-history/tracing-subscriber.git"
history_head = "86291ff1c974187a82c5d33b310940c01f1ed3a8"
materialized_path = "lib/vendor/tracing-subscriber"
sync_cmd = "scripts/vendor/inhouse-crate.sh tracing-subscriber 0.3.23"
