crate = "toml"
version = "1.0.6+spec-1.1.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "399b1124a3c9e16766831c6bba21e50192572cdd98706ea114f9502509686ffc"
crate_archive_sha256 = "399b1124a3c9e16766831c6bba21e50192572cdd98706ea114f9502509686ffc"
checksum_match = "yes"
upstream_repository = "https://github.com/toml-rs/toml"
upstream_homepage = ""
synced_at_utc = "2026-03-09T16:49:41Z"
history_repo = "lib/vendor-history/toml.git"
history_head = "86abe71bec028f0fdd6afdbe4f0f1eb2e0b41dd6"
sync_cmd = "scripts/vendor/inhouse-crate.sh toml 1.0.6+spec-1.1.0"
