crate = "portable-pty"
version = "0.9.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "b4a596a2b3d2752d94f51fac2d4a96737b8705dddd311a32b9af47211f08671e"
crate_archive_sha256 = "b4a596a2b3d2752d94f51fac2d4a96737b8705dddd311a32b9af47211f08671e"
checksum_match = "yes"
upstream_repository = "https://github.com/wezterm/wezterm"
upstream_homepage = ""
synced_at_utc = "2026-03-09T16:48:39Z"
history_repo = "lib/vendor-history/portable-pty.git"
history_head = "06a5eafe103dc7040e47ad88ae43f3cf52bbfc92"
sync_cmd = "scripts/vendor/inhouse-crate.sh portable-pty 0.9.0"
